apiVersion: v1
kind: Service
metadata:
  name: judge-flow
  namespace: nite-eval
  labels:
    app.kubernetes.io/name: judge-flow
    app.kubernetes.io/part-of: nite-eval
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: judge-flow
  ports:
    - name: http
      port: 9092
      targetPort: 9092
      protocol: TCP
