apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nite-eval-results
  namespace: nite-eval
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
